TBL_NAMES = {
    "CONFIG_AGE_BANDS_SET": "config_age_bands_set",
    "CONFIG_AGE_BANDS": "config_age_bands",
    "CONFIG_AGE_DISTRIBUTION": "config_age_distribution", 
    "CONFIG_AGE_DISTRIBUTION_SET": "config_age_distribution_set", 
    "CONFIG_ATTRIBUTE_DISTRIBUTION": "config_attr_distribution", 
    "CONFIG_ATTRIBUTE_DISTRIBUTION_SET": "config_attr_distribution_set", 
    "CONFIG_BENEFIT": "config_benefit",
    "CONFIG_BENEFIT_DURATION": "config_benefit_duration",
    "CONFIG_BENEFIT_DURATION_ITEM_STATE_AVAILABILITY": "config_benefit_duration_item_state_availability",
    "CONFIG_BENEFIT_DURATION_ITEMS": "config_benefit_duration_items",
    "CONFIG_BENEFIT_PROVISION_APPLICABILITY": "config_benefit_provision_applicability",
    "CONFIG_BENEFIT_PRODUCT_VARIATION_APPLICABILITY": "config_benefit_product_variation_applicability", 
    "CONFIG_BENEFIT_STATE_AVAILABILITY": "config_benefit_state_availability",
    "CONFIG_COVERAGE": "config_coverage",
    "CONFIG_COVERAGE_STATE_AVAILABILITY": "config_coverage_state_availability",
    "CONFIG_FACTOR": "config_factor",
    "CONFIG_FACTOR_RULE": "config_factor_rule",
    "CONFIG_PRODUCT": "config_product",
    "CONFIG_PRODUCT_STATE_AVAILABILITY": "config_product_state_availability",
    "CONFIG_PRODUCT_VARIATIONS": "config_product_variations",
    "CONFIG_PROVISION": "config_provision",
    "CONFIG_PROVISION_STATE_AVAILABILITY": "config_provision_state_availability",
    "CONFIG_PROVISION_UI_COMPONENT": "config_provision_ui_component",
    "CONFIG_RATE_GROUP": "config_rate_group", 
    "CONFIG_RATE_TABLE": "rate_table", 
    "REF_BENEFIT": "ref_benefit",
    "REF_BENEFIT_DURATION": "ref_benefit_duration",
    "REF_BENEFIT_DURATION_ITEMS": "ref_benefit_duration_items",
    'REF_COMPARISON_OPERATOR': "ref_comparison_operator",
    "REF_COMPONENT_TYPES": "ref_component_types",
    "REF_COVERAGE": "ref_coverage",
    "REF_INTERPOLATION_RULE": "ref_interpolation_rule",
    "REF_PRODUCT": "ref_product",
    "REF_PRODUCT_VARIATIONS": "ref_product_variations",
    "REF_PROVISION": "ref_provision",
    "REF_RATING_ALGORITHM": "ref_rating_algorithm",
    "REF_RATE_GROUP": "ref_rate_group", 
    "REF_RATE_TYPE": "ref_rate_type", 
    "REF_STATE": "ref_state",
    "REF_TEXT_FIELD_TYPES": "ref_text_field_types",
    "REF_UNIT_CODE": "ref_unit_code", 

    "SELECTION_AGE_BANDS": "selection_age_bands", 
    "SELECTION_BENEFIT": "selection_benefit", 
    "SELECTION_BENEFIT_AGE_RATE": "selection_benefit_age_rate", 
    "SELECTION_BENEFIT_DURATION": "selection_benefit_duration", 
    "SELECTION_BENEFIT_FACTOR": "selection_benefit_factor", 
    "SELECTION_BENEFIT_RATE": "selection_benefit_rate", 
    "SELECTION_DISTRIBUTION": "selection_distribution", 
    "SELECTION_PLAN": "selection_plan", 
    "SELECTION_PROVISION": "selection_provision", 
    "SELECTION_RATE_GROUP_SUMMARY": "selection_rate_group_summary", 
}


COVERAGE_SECTION_DEFAULT = 'main'

FACTOR_DECIMAL_PRECISION = 5
